version: '3.1'

services:

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: assignment1234
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - scg_assignment
    restart: always

volumes:
  db_data:
networks:
  scg_assignment:
